import { contextBridge, ipcRenderer } from 'electron'
import type { CreateTaskInput, OrbitaskApi, UpdateTaskInput } from '@orbitask/contracts'

const api: OrbitaskApi = {
  getSession:()=>ipcRenderer.invoke('auth:session'),
  signUp:(input)=>ipcRenderer.invoke('auth:signup',input),
  signIn:(input)=>ipcRenderer.invoke('auth:signin',input),
  signOut:()=>ipcRenderer.invoke('auth:signout'),
  getSnapshot: (projectId?:string) => projectId ? ipcRenderer.invoke('project:select',projectId) : ipcRenderer.invoke('workspace:snapshot'),
  createProject:(input)=>ipcRenderer.invoke('project:create',input),
  updateProject:(input)=>ipcRenderer.invoke('project:update',input),
  updateProjectSettings:(input)=>ipcRenderer.invoke('project:settings',input),
  updateProjectPreferences:(input)=>ipcRenderer.invoke('project:preferences',input),
  createTask: (input: CreateTaskInput) => ipcRenderer.invoke('task:create', input),
  updateTask: (input: UpdateTaskInput) => ipcRenderer.invoke('task:update', input),
  moveTask: (input) => ipcRenderer.invoke('task:move', input),
  trashTask: (id: string) => ipcRenderer.invoke('task:trash', id),
  createComment:(input)=>ipcRenderer.invoke('task:comment',input),
  addAttachment:(input)=>ipcRenderer.invoke('task:attachment:add',input),
  removeAttachment:(id)=>ipcRenderer.invoke('task:attachment:remove',id),
  createChecklistItem:(input)=>ipcRenderer.invoke('task:checklist:create',input),
  updateChecklistItem:(input)=>ipcRenderer.invoke('task:checklist:update',input),
  removeChecklistItem:(id)=>ipcRenderer.invoke('task:checklist:remove',id),
  addDependency:(input)=>ipcRenderer.invoke('task:dependency:add',input),
  removeDependency:(input)=>ipcRenderer.invoke('task:dependency:remove',input),
  updateCustomFields:(input)=>ipcRenderer.invoke('project:custom-fields',input),
  setTaskCustomField:(input)=>ipcRenderer.invoke('task:custom-field:set',input),
  listMembers:()=>ipcRenderer.invoke('workspace:members'),
  createInvite:(input)=>ipcRenderer.invoke('workspace:invite:create',input),
  revokeInvite:(id)=>ipcRenderer.invoke('workspace:invite:revoke',id),
  updateMember:(input)=>ipcRenderer.invoke('workspace:member:update',input),
  removeMember:(userId)=>ipcRenderer.invoke('workspace:member:remove',userId),
  updateProfile:(input)=>ipcRenderer.invoke('profile:update',input),
  listNotifications:()=>ipcRenderer.invoke('notifications:list'),
  markNotificationRead:(id)=>ipcRenderer.invoke('notifications:read',id),
  markAllNotificationsRead:()=>ipcRenderer.invoke('notifications:read-all'),
  listAutomations:(projectId)=>ipcRenderer.invoke('automations:list',projectId),
  saveAutomation:(input)=>ipcRenderer.invoke('automations:save',input),
  removeAutomation:(id)=>ipcRenderer.invoke('automations:remove',id),
  searchGlobal:(query)=>ipcRenderer.invoke('search:global',query),
  listSavedFilters:(projectId)=>ipcRenderer.invoke('filters:list',projectId),
  saveTaskFilter:(input)=>ipcRenderer.invoke('filters:save',input),
  removeSavedFilter:(id)=>ipcRenderer.invoke('filters:remove',id),
  getDashboard:()=>ipcRenderer.invoke('reports:dashboard'),
  getPortfolioOverview:()=>ipcRenderer.invoke('portfolio:overview'),
  savePortfolio:(input)=>ipcRenderer.invoke('portfolio:save',input),
  removePortfolio:(id)=>ipcRenderer.invoke('portfolio:remove',id),
  saveGoal:(input)=>ipcRenderer.invoke('goal:save',input),
  removeGoal:(id)=>ipcRenderer.invoke('goal:remove',id),
}

contextBridge.exposeInMainWorld('orbitask', api)
