import { randomUUID } from 'node:crypto'
import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import type { AutomationAction, AutomationRun, ProjectAutomation, SaveAutomationInput, WorkspaceRole } from '@orbitask/contracts'
import { DatabaseService } from './database.service.js'

interface AutomationRow {id:string;project_id:string;name:string;enabled:boolean;trigger_type:ProjectAutomation['trigger'];trigger_value:string|null;actions:AutomationAction[];created_at:string;updated_at:string}
const mapAutomation=(row:AutomationRow):ProjectAutomation=>({id:row.id,projectId:row.project_id,name:row.name,enabled:row.enabled,trigger:row.trigger_type,triggerValue:row.trigger_value,actions:row.actions,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()})

@Injectable()
export class AutomationsService {
  constructor(private readonly database:DatabaseService){}
  private async access(workspaceId:string,projectId:string,userId:string,role:WorkspaceRole){const result=await this.database.query(`SELECT 1 FROM projects p WHERE p.id=$1 AND p.workspace_id=$2 AND ($4<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[projectId,workspaceId,userId,role]);if(!result.rowCount)throw new NotFoundException('Projeto não encontrado')}
  async list(workspaceId:string,projectId:string,userId:string,role:WorkspaceRole){await this.access(workspaceId,projectId,userId,role);const automations=await this.database.query<AutomationRow>('SELECT * FROM project_automations WHERE project_id=$1 ORDER BY created_at',[projectId]);const ids=automations.rows.map(item=>item.id);const runs=ids.length?await this.database.query<{id:string;automation_id:string;task_id:string|null;status:'success'|'error';message:string;created_at:string}>('SELECT * FROM automation_runs WHERE automation_id=ANY($1::uuid[]) ORDER BY created_at DESC LIMIT 50',[ids]):{rows:[]};return{automations:automations.rows.map(mapAutomation),runs:runs.rows.map(row=>({id:row.id,automationId:row.automation_id,taskId:row.task_id,status:row.status,message:row.message,createdAt:new Date(row.created_at).toISOString()} satisfies AutomationRun))}}
  async save(workspaceId:string,userId:string,role:WorkspaceRole,input:SaveAutomationInput){if(role!=='admin')throw new ForbiddenException('Somente administradores podem alterar automações');await this.access(workspaceId,input.projectId,userId,role);if(!input.name?.trim())throw new BadRequestException('Informe o nome da automação');if(!input.actions?.length)throw new BadRequestException('Adicione pelo menos uma ação');if(input.actions.some(action=>!action.value?.trim()))throw new BadRequestException('Configure o valor de todas as ações');const id=input.id??randomUUID();const result=await this.database.query<AutomationRow>(`INSERT INTO project_automations(id,project_id,name,enabled,trigger_type,trigger_value,actions) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,enabled=EXCLUDED.enabled,trigger_type=EXCLUDED.trigger_type,trigger_value=EXCLUDED.trigger_value,actions=EXCLUDED.actions,updated_at=NOW() WHERE project_automations.project_id=EXCLUDED.project_id RETURNING *`,[id,input.projectId,input.name.trim(),input.enabled,input.trigger,input.triggerValue??null,JSON.stringify(input.actions)]);if(!result.rows[0])throw new NotFoundException('Automação não encontrada');return mapAutomation(result.rows[0])}
  async remove(workspaceId:string,userId:string,role:WorkspaceRole,id:string){if(role!=='admin')throw new ForbiddenException('Somente administradores podem excluir automações');const result=await this.database.query(`DELETE FROM project_automations a USING projects p WHERE a.id=$1 AND a.project_id=p.id AND p.workspace_id=$2`,[id,workspaceId]);if(!result.rowCount)throw new NotFoundException('Automação não encontrada')}
  async run(projectId:string,taskId:string,trigger:ProjectAutomation['trigger'],triggerValue:string|null,userId:string){const result=await this.database.query<AutomationRow>(`SELECT * FROM project_automations WHERE project_id=$1 AND enabled=TRUE AND trigger_type=$2 AND (trigger_value IS NULL OR trigger_value=$3)`,[projectId,trigger,triggerValue]);for(const automation of result.rows){try{await this.database.transaction(async query=>{for(const action of automation.actions){if(action.type==='set_status')await query('UPDATE tasks SET status_id=$2,updated_at=NOW() WHERE id=$1',[taskId,action.value]);if(action.type==='set_priority')await query('UPDATE tasks SET priority=$2,updated_at=NOW() WHERE id=$1',[taskId,action.value]);if(action.type==='assign_user'){await query('INSERT INTO task_assignees(task_id,user_id,is_primary) VALUES($1,$2,FALSE) ON CONFLICT DO NOTHING',[taskId,action.value]);await query('INSERT INTO task_followers(task_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[taskId,action.value])}if(action.type==='add_tag')await query('INSERT INTO task_tags(task_id,tag_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[taskId,action.value]);if(action.type==='set_due_days')await query(`UPDATE tasks SET due_date=CURRENT_DATE+$2::int,updated_at=NOW() WHERE id=$1`,[taskId,Number(action.value)]);if(action.type==='create_subtask'){const firstStatus=await query<{id:string}>('SELECT id FROM statuses WHERE project_id=$1 ORDER BY position LIMIT 1',[projectId]);await query('INSERT INTO tasks(id,project_id,parent_id,title,status_id,priority,position) SELECT $1,project_id,id,$2,$3,priority,$4 FROM tasks WHERE id=$5',[randomUUID(),action.value,firstStatus.rows[0]?.id,Date.now(),taskId])}}await query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'automation_executed',JSON.stringify({automationId:automation.id,name:automation.name}),userId]);await query('INSERT INTO automation_runs(id,automation_id,task_id,status,message) VALUES($1,$2,$3,$4,$5)',[randomUUID(),automation.id,taskId,'success',`${automation.actions.length} ação(ões) executada(s)`])})}catch(error){await this.database.query('INSERT INTO automation_runs(id,automation_id,task_id,status,message) VALUES($1,$2,$3,$4,$5)',[randomUUID(),automation.id,taskId,'error',error instanceof Error?error.message:'Falha inesperada'])}}
  }
}
