import { randomUUID } from 'node:crypto'
import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'
import type { DashboardProjectMetric, DashboardReport, Goal, GoalStatus, Portfolio, PortfolioHealth, PortfolioOverview, SaveGoalInput, SavePortfolioInput, WorkspaceRole } from '@orbitask/contracts'
import { DatabaseService } from './database.service.js'

interface MetricRow {id:string;name:string;color:string;icon:string;total:string;completed:string;overdue:string}
interface PortfolioRow {id:string;workspace_id:string;name:string;description:string;color:string;owner_id:string|null;start_date:string|null;due_date:string|null;health:PortfolioHealth;project_ids:string[];created_at:string;updated_at:string}
interface GoalRow {id:string;workspace_id:string;title:string;description:string;status:GoalStatus;progress:number;owner_id:string|null;due_date:string|null;project_ids:string[];created_at:string;updated_at:string}
const iso=(value:string|null)=>value?String(value).slice(0,10):null
const metric=(row:MetricRow):DashboardProjectMetric=>{const total=Number(row.total),completed=Number(row.completed);return{id:row.id,name:row.name,color:row.color,icon:row.icon,total,completed,overdue:Number(row.overdue),progress:total?Math.round(completed/total*100):0}}
const portfolio=(row:PortfolioRow):Portfolio=>({id:row.id,workspaceId:row.workspace_id,name:row.name,description:row.description,color:row.color,ownerId:row.owner_id,startDate:iso(row.start_date),dueDate:iso(row.due_date),projectIds:row.project_ids??[],health:row.health,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()})
const goal=(row:GoalRow):Goal=>({id:row.id,workspaceId:row.workspace_id,title:row.title,description:row.description,status:row.status,progress:Number(row.progress),ownerId:row.owner_id,dueDate:iso(row.due_date),projectIds:row.project_ids??[],createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()})

@Injectable()
export class InsightsService {
  constructor(private readonly database:DatabaseService){}
  private access(role:WorkspaceRole){return role==='guest'?'AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$2)':''}
  private async projectMetrics(workspaceId:string,userId:string,role:WorkspaceRole){const rows=await this.database.query<MetricRow>(`SELECT p.id::text,p.name,p.color,p.icon,COUNT(t.id)::text total,COUNT(t.id) FILTER(WHERE s.position=maxs.last_position)::text completed,COUNT(t.id) FILTER(WHERE t.due_date<CURRENT_DATE AND s.position<>maxs.last_position)::text overdue FROM projects p LEFT JOIN LATERAL(SELECT MAX(position) last_position FROM statuses WHERE project_id=p.id) maxs ON TRUE LEFT JOIN tasks t ON t.project_id=p.id AND t.deleted_at IS NULL AND t.parent_id IS NULL LEFT JOIN statuses s ON s.id=t.status_id WHERE p.workspace_id=$1 ${this.access(role)} GROUP BY p.id,maxs.last_position ORDER BY p.created_at`,role==='guest'?[workspaceId,userId]:[workspaceId]);return rows.rows.map(metric)}
  async dashboard(workspaceId:string,userId:string,role:WorkspaceRole):Promise<DashboardReport>{
    const access=this.access(role),params=role==='guest'?[workspaceId,userId]:[workspaceId]
    const [totals,statuses,priorities,assignees,projects]=await Promise.all([
      this.database.query<{projects:string;tasks:string;active:string;completed:string;overdue:string;due_soon:string}>(`SELECT COUNT(DISTINCT p.id)::text projects,COUNT(t.id)::text tasks,COUNT(t.id) FILTER(WHERE s.position<>maxs.last_position)::text active,COUNT(t.id) FILTER(WHERE s.position=maxs.last_position)::text completed,COUNT(t.id) FILTER(WHERE t.due_date<CURRENT_DATE AND s.position<>maxs.last_position)::text overdue,COUNT(t.id) FILTER(WHERE t.due_date BETWEEN CURRENT_DATE AND CURRENT_DATE+7 AND s.position<>maxs.last_position)::text due_soon FROM projects p LEFT JOIN LATERAL(SELECT MAX(position) last_position FROM statuses WHERE project_id=p.id) maxs ON TRUE LEFT JOIN tasks t ON t.project_id=p.id AND t.deleted_at IS NULL AND t.parent_id IS NULL LEFT JOIN statuses s ON s.id=t.status_id WHERE p.workspace_id=$1 ${access}`,params),
      this.database.query<{id:string;name:string;color:string;count:string}>(`SELECT LOWER(REPLACE(s.name,' ','-')) id,s.name,s.color,COUNT(t.id)::text count FROM projects p JOIN statuses s ON s.project_id=p.id LEFT JOIN tasks t ON t.project_id=p.id AND t.status_id=s.id AND t.deleted_at IS NULL AND t.parent_id IS NULL WHERE p.workspace_id=$1 ${access} GROUP BY s.name,s.color,s.position ORDER BY s.position`,params),
      this.database.query<{id:string;name:string;color:string;count:string}>(`SELECT pp.id,pp.name,pp.color,COUNT(t.id)::text count FROM projects p JOIN project_priorities pp ON pp.project_id=p.id LEFT JOIN tasks t ON t.project_id=p.id AND t.priority=pp.id AND t.deleted_at IS NULL AND t.parent_id IS NULL WHERE p.workspace_id=$1 ${access} GROUP BY pp.id,pp.name,pp.color,pp.position ORDER BY pp.position`,params),
      this.database.query<{id:string;name:string;avatar_url:string|null;count:string;completed:string;overdue:string}>(`SELECT u.id::text,u.name,u.avatar_url,COUNT(DISTINCT t.id)::text count,COUNT(DISTINCT t.id) FILTER(WHERE s.position=maxs.last_position)::text completed,COUNT(DISTINCT t.id) FILTER(WHERE t.due_date<CURRENT_DATE AND s.position<>maxs.last_position)::text overdue FROM projects p JOIN tasks t ON t.project_id=p.id AND t.deleted_at IS NULL AND t.parent_id IS NULL JOIN task_assignees ta ON ta.task_id=t.id JOIN users u ON u.id=ta.user_id JOIN statuses s ON s.id=t.status_id LEFT JOIN LATERAL(SELECT MAX(position) last_position FROM statuses WHERE project_id=p.id) maxs ON TRUE WHERE p.workspace_id=$1 ${access} GROUP BY u.id,u.name,u.avatar_url ORDER BY count DESC,u.name`,params),
      this.projectMetrics(workspaceId,userId,role)
    ])
    const t=totals.rows[0];return{totals:{projects:Number(t.projects),tasks:Number(t.tasks),active:Number(t.active),completed:Number(t.completed),overdue:Number(t.overdue),dueSoon:Number(t.due_soon)},byStatus:statuses.rows.map(x=>({...x,count:Number(x.count)})),byPriority:priorities.rows.map(x=>({...x,count:Number(x.count)})),byAssignee:assignees.rows.map(x=>({id:x.id,name:x.name,avatarUrl:x.avatar_url,count:Number(x.count),completed:Number(x.completed),overdue:Number(x.overdue)})),projects}
  }
  private async lists(workspaceId:string){const [p,g]=await Promise.all([this.database.query<PortfolioRow>(`SELECT x.*,COALESCE(array_agg(pp.project_id::text ORDER BY pp.project_id) FILTER(WHERE pp.project_id IS NOT NULL),'{}') project_ids FROM portfolios x LEFT JOIN portfolio_projects pp ON pp.portfolio_id=x.id WHERE x.workspace_id=$1 GROUP BY x.id ORDER BY x.updated_at DESC`,[workspaceId]),this.database.query<GoalRow>(`SELECT x.*,COALESCE(array_agg(gp.project_id::text ORDER BY gp.project_id) FILTER(WHERE gp.project_id IS NOT NULL),'{}') project_ids FROM goals x LEFT JOIN goal_projects gp ON gp.goal_id=x.id WHERE x.workspace_id=$1 GROUP BY x.id ORDER BY x.updated_at DESC`,[workspaceId])]);return{portfolios:p.rows.map(portfolio),goals:g.rows.map(goal)}}
  async overview(workspaceId:string,userId:string,role:WorkspaceRole):Promise<PortfolioOverview>{const [lists,projectMetrics]=await Promise.all([this.lists(workspaceId),this.projectMetrics(workspaceId,userId,role)]);const allowed=new Set(projectMetrics.map(x=>x.id));return{portfolios:lists.portfolios.map(x=>({...x,projectIds:x.projectIds.filter(id=>allowed.has(id))})),goals:lists.goals.map(x=>({...x,projectIds:x.projectIds.filter(id=>allowed.has(id))})),projectMetrics}}
  private admin(role:WorkspaceRole){if(role!=='admin')throw new ForbiddenException('Somente administradores podem alterar portfólios e metas')}
  private async validateProjects(workspaceId:string,ids:string[]){if(!ids.length)return;const result=await this.database.query<{count:string}>('SELECT COUNT(*)::text count FROM projects WHERE workspace_id=$1 AND id=ANY($2::uuid[])',[workspaceId,ids]);if(Number(result.rows[0].count)!==new Set(ids).size)throw new BadRequestException('Um ou mais projetos não pertencem ao workspace')}
  async savePortfolio(workspaceId:string,role:WorkspaceRole,input:SavePortfolioInput){this.admin(role);if(!input.name?.trim())throw new BadRequestException('Informe o nome do portfólio');if(!/^#[0-9a-f]{6}$/i.test(input.color))throw new BadRequestException('Cor inválida');const ids=[...new Set(input.projectIds??[])];await this.validateProjects(workspaceId,ids);const id=input.id??randomUUID(),health=input.health??'on_track';if(!['on_track','at_risk','off_track','on_hold'].includes(health))throw new BadRequestException('Saúde inválida');await this.database.transaction(async q=>{const saved=await q(`INSERT INTO portfolios(id,workspace_id,name,description,color,owner_id,start_date,due_date,health) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,color=EXCLUDED.color,owner_id=EXCLUDED.owner_id,start_date=EXCLUDED.start_date,due_date=EXCLUDED.due_date,health=EXCLUDED.health,updated_at=NOW() WHERE portfolios.workspace_id=EXCLUDED.workspace_id`,[id,workspaceId,input.name.trim(),input.description?.trim()??'',input.color,input.ownerId??null,input.startDate??null,input.dueDate??null,health]);if(input.id&&!saved.rowCount)throw new NotFoundException('Portfólio não encontrado');await q('DELETE FROM portfolio_projects WHERE portfolio_id=$1',[id]);for(const projectId of ids)await q('INSERT INTO portfolio_projects(portfolio_id,project_id) VALUES($1,$2)',[id,projectId])});return (await this.lists(workspaceId)).portfolios.find(x=>x.id===id)!}
  async removePortfolio(workspaceId:string,role:WorkspaceRole,id:string){this.admin(role);const result=await this.database.query('DELETE FROM portfolios WHERE id=$1 AND workspace_id=$2',[id,workspaceId]);if(!result.rowCount)throw new NotFoundException('Portfólio não encontrado')}
  async saveGoal(workspaceId:string,role:WorkspaceRole,input:SaveGoalInput){this.admin(role);if(!input.title?.trim())throw new BadRequestException('Informe o título da meta');const progress=Math.max(0,Math.min(100,Number(input.progress)||0)),ids=[...new Set(input.projectIds??[])];await this.validateProjects(workspaceId,ids);if(!['not_started','on_track','at_risk','completed'].includes(input.status))throw new BadRequestException('Status inválido');const id=input.id??randomUUID();await this.database.transaction(async q=>{const saved=await q(`INSERT INTO goals(id,workspace_id,title,description,status,progress,owner_id,due_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,status=EXCLUDED.status,progress=EXCLUDED.progress,owner_id=EXCLUDED.owner_id,due_date=EXCLUDED.due_date,updated_at=NOW() WHERE goals.workspace_id=EXCLUDED.workspace_id`,[id,workspaceId,input.title.trim(),input.description?.trim()??'',input.status,progress,input.ownerId??null,input.dueDate??null]);if(input.id&&!saved.rowCount)throw new NotFoundException('Meta não encontrada');await q('DELETE FROM goal_projects WHERE goal_id=$1',[id]);for(const projectId of ids)await q('INSERT INTO goal_projects(goal_id,project_id) VALUES($1,$2)',[id,projectId])});return (await this.lists(workspaceId)).goals.find(x=>x.id===id)!}
  async removeGoal(workspaceId:string,role:WorkspaceRole,id:string){this.admin(role);const result=await this.database.query('DELETE FROM goals WHERE id=$1 AND workspace_id=$2',[id,workspaceId]);if(!result.rowCount)throw new NotFoundException('Meta não encontrada')}
}
