import { randomUUID } from 'node:crypto'
import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common'
import type { CreateTaskInput, CustomFieldDefinition, CustomFieldOption, CustomFieldType, Task, TaskAttachment, TaskChecklistItem, TaskComment, TaskCustomFieldValue, TaskDependency, UpdateTaskInput, WorkspaceRole, WorkspaceSnapshot } from '@orbitask/contracts'
import { DatabaseService } from './database.service.js'
import { ProjectsService, mapProject } from './projects.service.js'
import { CollaborationService } from './collaboration.service.js'
import { AutomationsService } from './automations.service.js'

interface TaskRow { id:string; project_id:string; parent_id:string|null; title:string; description:string; status_id:string; priority:Task['priority']; start_date:string|null; due_date:string|null; position:number; deleted_at:string|null; created_at:string; updated_at:string }
const mapTask = (row: TaskRow,tagIds:string[]=[],badgeIds:string[]=[],assigneeIds:string[]=[],primaryAssigneeId:string|null=null,followerIds:string[]=[]): Task => ({ id:row.id, projectId:row.project_id, parentId:row.parent_id, title:row.title, description:row.description, statusId:row.status_id, priority:row.priority, startDate:row.start_date ? new Date(row.start_date).toISOString().slice(0,10) : null, dueDate:row.due_date ? new Date(row.due_date).toISOString().slice(0,10) : null, position:Number(row.position), deletedAt:row.deleted_at, createdAt:new Date(row.created_at).toISOString(), updatedAt:new Date(row.updated_at).toISOString(),tagIds,badgeIds,assigneeIds,primaryAssigneeId,followerIds })

@Injectable()
export class TasksService {
  constructor(private readonly database: DatabaseService,private readonly projectsService:ProjectsService,private readonly collaboration:CollaborationService,private readonly automations:AutomationsService) {}

  private async assertProjectAccess(workspaceId:string,projectId:string,userId:string,role:WorkspaceRole){const result=await this.database.query(`SELECT 1 FROM projects p WHERE p.id=$1 AND p.workspace_id=$2 AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[projectId,workspaceId,userId,role]);if(!result.rowCount)throw new NotFoundException('Projeto não encontrado')}
  private async validatePeople(projectId:string,userIds:string[]){if(!userIds.length)return;const unique=[...new Set(userIds)];const result=await this.database.query(`SELECT u.id FROM users u JOIN workspace_members wm ON wm.user_id=u.id JOIN projects p ON p.workspace_id=wm.workspace_id WHERE p.id=$1 AND u.id=ANY($2::uuid[]) AND (wm.role<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=u.id))`,[projectId,unique]);if(result.rowCount!==unique.length)throw new BadRequestException('Um dos usuários não possui acesso ao projeto')}

  async snapshot(userId:string,workspace:{id:string;name:string;role:'admin'|'member'|'guest'},projectId?:string): Promise<WorkspaceSnapshot> {
    const projectResult = await this.database.query<{id:string;workspace_id:string;name:string;description:string;color:string;icon:string;created_at:string}>(`SELECT p.* FROM projects p WHERE p.workspace_id=$1 AND ($2::uuid IS NULL OR p.id=$2) AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3)) ORDER BY p.created_at LIMIT 1`,[workspace.id,projectId??null,userId,workspace.role])
    const project = projectResult.rows[0]
    if (!project) throw new NotFoundException('Workspace não inicializado')
    const settings=await this.projectsService.ensureSettings(project.id)
    const [statusResult, taskResult,tagResult,badgeResult,assigneeResult,followerResult,commentResult,attachmentResult,checklistResult,dependencyResult,customFieldsResult,customValuesResult,activityResult] = await Promise.all([
      this.database.query<{id:string;name:string;color:string;position:number}>('SELECT id,name,color,position FROM statuses WHERE project_id=$1 ORDER BY position',[project.id]),
      this.database.query<TaskRow>('SELECT * FROM tasks WHERE project_id=$1 AND deleted_at IS NULL ORDER BY position', [project.id]),
      this.database.query<{task_id:string;id:string}>('SELECT tt.task_id,tt.tag_id::text id FROM task_tags tt JOIN tasks t ON t.id=tt.task_id WHERE t.project_id=$1',[project.id]),
      this.database.query<{task_id:string;id:string}>('SELECT tb.task_id,tb.badge_id::text id FROM task_badges tb JOIN tasks t ON t.id=tb.task_id WHERE t.project_id=$1',[project.id]),
      this.database.query<{task_id:string;user_id:string;is_primary:boolean}>('SELECT ta.task_id,ta.user_id::text,ta.is_primary FROM task_assignees ta JOIN tasks t ON t.id=ta.task_id WHERE t.project_id=$1',[project.id]),
      this.database.query<{task_id:string;user_id:string}>('SELECT tf.task_id,tf.user_id::text FROM task_followers tf JOIN tasks t ON t.id=tf.task_id WHERE t.project_id=$1',[project.id]),
      this.database.query<{id:string;task_id:string;user_id:string;author_name:string;body:string;created_at:string}>('SELECT c.id,c.task_id,c.user_id,u.name author_name,c.body,c.created_at FROM task_comments c JOIN users u ON u.id=c.user_id JOIN tasks t ON t.id=c.task_id WHERE t.project_id=$1 ORDER BY c.created_at',[project.id]),
      this.database.query<{id:string;task_id:string;name:string;url:string;created_at:string}>('SELECT a.* FROM task_attachments a JOIN tasks t ON t.id=a.task_id WHERE t.project_id=$1 ORDER BY a.created_at',[project.id]),
      this.database.query<{id:string;task_id:string;title:string;completed:boolean;position:number;created_at:string}>('SELECT c.* FROM task_checklist_items c JOIN tasks t ON t.id=c.task_id WHERE t.project_id=$1 ORDER BY c.position,c.created_at',[project.id]),
      this.database.query<{task_id:string;depends_on_task_id:string;created_at:string}>('SELECT d.* FROM task_dependencies d JOIN tasks t ON t.id=d.task_id WHERE t.project_id=$1 ORDER BY d.created_at',[project.id]),
      this.database.query<{id:string;project_id:string;name:string;type:CustomFieldType;options:CustomFieldOption[];position:number}>('SELECT id::text,project_id::text,name,type,options,position FROM project_custom_fields WHERE project_id=$1 ORDER BY position',[project.id]),
      this.database.query<{task_id:string;field_id:string;value:string|number|string[]|null}>('SELECT v.task_id::text,v.field_id::text,v.value FROM task_custom_field_values v JOIN tasks t ON t.id=v.task_id WHERE t.project_id=$1',[project.id]),
      this.database.query<{id:string;entity_id:string;action:string;payload:Record<string,unknown>;author_name:string|null;created_at:string}>('SELECT a.id,a.entity_id,a.action,a.payload,u.name author_name,a.created_at FROM activity_log a LEFT JOIN users u ON u.id=a.user_id JOIN tasks t ON t.id=a.entity_id WHERE a.entity_type=\'task\' AND t.project_id=$1 ORDER BY a.created_at DESC',[project.id]),
    ])
    const [projects,userResult,preferences,team]=await Promise.all([this.projectsService.list(workspace.id,userId,workspace.role),this.database.query<{id:string;name:string;email:string;avatar_url:string|null;created_at:string}>('SELECT id,name,email,avatar_url,created_at FROM users WHERE id=$1',[userId]),this.projectsService.getPreferences(userId,project.id),this.collaboration.list(workspace.id,workspace.role)])
    const user=userResult.rows[0]
    const relationIds=(rows:{task_id:string;id:string}[],taskId:string)=>rows.filter(item=>item.task_id===taskId).map(item=>item.id)
    return {workspace, user:{id:user.id,name:user.name,email:user.email,avatarUrl:user.avatar_url,createdAt:new Date(user.created_at).toISOString()},project:mapProject(project),projects,statuses: statusResult.rows,settings,preferences,members:team.members,invites:team.invites,tasks:taskResult.rows.map(row=>{const assigned=assigneeResult.rows.filter(item=>item.task_id===row.id);return mapTask(row,relationIds(tagResult.rows,row.id),relationIds(badgeResult.rows,row.id),assigned.map(item=>item.user_id),assigned.find(item=>item.is_primary)?.user_id??null,followerResult.rows.filter(item=>item.task_id===row.id).map(item=>item.user_id))}),comments:commentResult.rows.map(row=>({id:row.id,taskId:row.task_id,userId:row.user_id,authorName:row.author_name,body:row.body,createdAt:new Date(row.created_at).toISOString()})),attachments:attachmentResult.rows.map(row=>({id:row.id,taskId:row.task_id,name:row.name,url:row.url,createdAt:new Date(row.created_at).toISOString()})),checklistItems:checklistResult.rows.map(row=>({id:row.id,taskId:row.task_id,title:row.title,completed:row.completed,position:row.position,createdAt:new Date(row.created_at).toISOString()})),dependencies:dependencyResult.rows.map(row=>({taskId:row.task_id,dependsOnTaskId:row.depends_on_task_id,createdAt:new Date(row.created_at).toISOString()})),customFields:customFieldsResult.rows.map(row=>({id:row.id,projectId:row.project_id,name:row.name,type:row.type,options:row.options,position:row.position})),customFieldValues:customValuesResult.rows.map(row=>({taskId:row.task_id,fieldId:row.field_id,value:row.value})),activities:activityResult.rows.map(row=>({id:row.id,taskId:row.entity_id,action:row.action,payload:row.payload,authorName:row.author_name,createdAt:new Date(row.created_at).toISOString()})) }
  }

  async create(workspaceId:string,input: CreateTaskInput,userId:string,role:WorkspaceRole): Promise<Task> {
    if (!input.title?.trim()) throw new BadRequestException('O título da tarefa é obrigatório')
    await this.assertProjectAccess(workspaceId,input.projectId,userId,role)
    if(input.parentId){const parent=await this.database.query('SELECT 1 FROM tasks WHERE id=$1 AND project_id=$2 AND deleted_at IS NULL',[input.parentId,input.projectId]);if(!parent.rowCount)throw new BadRequestException('A tarefa principal não pertence a este projeto')}
    const defaultPriority=await this.database.query<{id:string}>('SELECT id FROM project_priorities WHERE project_id=$1 ORDER BY position LIMIT 1',[input.projectId])
    const id = randomUUID()
    const created=await this.database.transaction(async (query) => {
      const result = await query<TaskRow>(`INSERT INTO tasks (id,project_id,parent_id,title,status_id,priority,position) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`, [id,input.projectId,input.parentId??null,input.title.trim(),input.statusId,input.priority??defaultPriority.rows[0]?.id??'medium',Date.now()])
      await query('INSERT INTO activity_log (id,entity_type,entity_id,action,payload,user_id) VALUES ($1,$2,$3,$4,$5,$6)', [randomUUID(),'task',id,input.parentId?'subtask_created':'created',JSON.stringify(input),userId??null])
      await query('INSERT INTO task_assignees (task_id,user_id,is_primary) VALUES ($1,$2,TRUE)',[id,userId])
      await query('INSERT INTO task_followers (task_id,user_id) VALUES ($1,$2)',[id,userId])
      return mapTask(result.rows[0],[],[],[userId],userId,[userId])
    })
    await this.automations.run(created.projectId,created.id,'task_created',null,userId)
    return created
  }

  async update(workspaceId:string,input: UpdateTaskInput,userId:string,role:WorkspaceRole): Promise<Task> {
    const fields: string[] = []; const values: unknown[] = []
    if(input.startDate&&input.dueDate&&input.startDate>input.dueDate)throw new BadRequestException('A data de início não pode ser posterior ao término')
    const mapping: Array<[keyof UpdateTaskInput,string]> = [['title','title'],['description','description'],['statusId','status_id'],['priority','priority'],['startDate','start_date'],['dueDate','due_date'],['position','position']]
    for (const [key,column] of mapping) if (input[key] !== undefined) { values.push(input[key]); fields.push(`${column}=$${values.length}`) }
    if (!fields.length&&input.tagIds===undefined&&input.badgeIds===undefined&&input.assigneeIds===undefined&&input.followerIds===undefined&&input.primaryAssigneeId===undefined) throw new BadRequestException('Nenhuma alteração enviada')
    values.push(input.id)
    const updated=await this.database.transaction(async (query) => {
      values.push(workspaceId)
      const updateSql=fields.length?`UPDATE tasks SET ${fields.join(',')},updated_at=NOW() WHERE id=$${values.length-1} AND deleted_at IS NULL AND project_id IN (SELECT p.id FROM projects p WHERE p.workspace_id=$${values.length} AND ($${values.length+2}<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$${values.length+1}))) RETURNING *`:`SELECT t.* FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=$${values.length-1} AND t.deleted_at IS NULL AND p.workspace_id=$${values.length} AND ($${values.length+2}<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$${values.length+1}))`
      const result = await query<TaskRow>(updateSql, [...values,userId,role])
      if (!result.rows[0]) throw new NotFoundException('Tarefa não encontrada')
      if(input.tagIds!==undefined){await query('DELETE FROM task_tags WHERE task_id=$1',[input.id]);for(const id of input.tagIds)await query('INSERT INTO task_tags (task_id,tag_id) SELECT $1,$2::uuid WHERE EXISTS (SELECT 1 FROM project_tags WHERE id=$2::uuid AND project_id=$3)',[input.id,id,result.rows[0].project_id])}
      if(input.badgeIds!==undefined){await query('DELETE FROM task_badges WHERE task_id=$1',[input.id]);for(const id of input.badgeIds)await query('INSERT INTO task_badges (task_id,badge_id) SELECT $1,$2::uuid WHERE EXISTS (SELECT 1 FROM project_badges WHERE id=$2::uuid AND project_id=$3)',[input.id,id,result.rows[0].project_id])}
      const assigneeIds=input.assigneeIds===undefined?null:[...new Set(input.assigneeIds)]
      const followerIds=input.followerIds===undefined?null:[...new Set(input.followerIds)]
      if(input.primaryAssigneeId&&!assigneeIds?.includes(input.primaryAssigneeId)){if(assigneeIds)assigneeIds.unshift(input.primaryAssigneeId)}
      await this.validatePeople(result.rows[0].project_id,[...(assigneeIds??[]),...(followerIds??[]),...(input.primaryAssigneeId?[input.primaryAssigneeId]:[])])
      if(assigneeIds!==null){await query('DELETE FROM task_assignees WHERE task_id=$1',[input.id]);for(const id of assigneeIds)await query('INSERT INTO task_assignees (task_id,user_id,is_primary) VALUES ($1,$2,$3)',[input.id,id,id===(input.primaryAssigneeId??assigneeIds[0])])}
      else if(input.primaryAssigneeId!==undefined){await query('UPDATE task_assignees SET is_primary=FALSE WHERE task_id=$1',[input.id]);if(input.primaryAssigneeId)await query('INSERT INTO task_assignees (task_id,user_id,is_primary) VALUES ($1,$2,TRUE) ON CONFLICT (task_id,user_id) DO UPDATE SET is_primary=TRUE',[input.id,input.primaryAssigneeId])}
      if(followerIds!==null){await query('DELETE FROM task_followers WHERE task_id=$1',[input.id]);for(const id of followerIds)await query('INSERT INTO task_followers (task_id,user_id) VALUES ($1,$2)',[input.id,id])}
      await query('INSERT INTO activity_log (id,entity_type,entity_id,action,payload,user_id) VALUES ($1,$2,$3,$4,$5,$6)', [randomUUID(),'task',input.id,'updated',JSON.stringify(input),userId??null])
      const tags=await query<{id:string}>('SELECT tag_id::text id FROM task_tags WHERE task_id=$1',[input.id])
      const badges=await query<{id:string}>('SELECT badge_id::text id FROM task_badges WHERE task_id=$1',[input.id])
      const assignees=await query<{id:string;is_primary:boolean}>('SELECT user_id::text id,is_primary FROM task_assignees WHERE task_id=$1',[input.id])
      const followers=await query<{id:string}>('SELECT user_id::text id FROM task_followers WHERE task_id=$1',[input.id])
      return mapTask(result.rows[0],tags.rows.map(item=>item.id),badges.rows.map(item=>item.id),assignees.rows.map(item=>item.id),assignees.rows.find(item=>item.is_primary)?.id??null,followers.rows.map(item=>item.id))
    })
    if(input.statusId!==undefined)await this.automations.run(updated.projectId,updated.id,'status_changed',input.statusId,userId)
    const refreshed=await this.database.query<TaskRow>('SELECT * FROM tasks WHERE id=$1',[updated.id])
    return refreshed.rows[0]?{...updated,...mapTask(refreshed.rows[0],updated.tagIds,updated.badgeIds,updated.assigneeIds,updated.primaryAssigneeId,updated.followerIds)}:updated
  }

  async trash(workspaceId:string,userId:string,role:WorkspaceRole,id: string): Promise<void> {
    const result = await this.database.query(`UPDATE tasks SET deleted_at=NOW(),updated_at=NOW() WHERE id=$1 AND deleted_at IS NULL AND project_id IN (SELECT p.id FROM projects p WHERE p.workspace_id=$2 AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3)))`, [id,workspaceId,userId,role])
    if (!result.rowCount) throw new NotFoundException('Tarefa não encontrada')
  }

  async createComment(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,body:string):Promise<TaskComment>{
    if(!body?.trim())throw new BadRequestException('Escreva um comentário')
    const allowed=await this.database.query(`SELECT 1 FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=$1 AND p.workspace_id=$2 AND t.deleted_at IS NULL AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[taskId,workspaceId,userId,role]);if(!allowed.rowCount)throw new NotFoundException('Tarefa não encontrada')
    const id=randomUUID();const result=await this.database.transaction(async query=>{const comment=await query<{id:string;task_id:string;user_id:string;body:string;created_at:string}>(`INSERT INTO task_comments (id,task_id,user_id,body) VALUES ($1,$2,$3,$4) RETURNING *`,[id,taskId,userId,body.trim()]);await query('INSERT INTO activity_log (id,entity_type,entity_id,action,payload,user_id) VALUES ($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'commented',JSON.stringify({commentId:id}),userId]);const mentioned=await query<{id:string}>(`SELECT u.id FROM users u JOIN workspace_members wm ON wm.user_id=u.id WHERE wm.workspace_id=$1 AND u.id<>$2 AND POSITION('@'||LOWER(u.name) IN LOWER($3))>0`,[workspaceId,userId,body]);for(const member of mentioned.rows){await query('INSERT INTO task_followers(task_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[taskId,member.id]);await query(`INSERT INTO notifications(id,user_id,task_id,project_id,type,title,message) SELECT $1,$2,t.id,t.project_id,'mentioned',t.title,'Você foi mencionado em um comentário' FROM tasks t WHERE t.id=$3`,[randomUUID(),member.id,taskId])}return comment.rows[0]});const author=await this.database.query<{name:string}>('SELECT name FROM users WHERE id=$1',[userId]);return{id:result.id,taskId:result.task_id,userId:result.user_id,authorName:author.rows[0].name,body:result.body,createdAt:new Date(result.created_at).toISOString()}
  }

  async addAttachment(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,input:{name:string;url:string}):Promise<TaskAttachment>{
    if(!input.name?.trim()||!input.url?.trim())throw new BadRequestException('Nome e endereço do anexo são obrigatórios')
    try{new URL(input.url)}catch{throw new BadRequestException('Informe um endereço válido, incluindo https://')}
    const allowed=await this.database.query(`SELECT 1 FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=$1 AND p.workspace_id=$2 AND t.deleted_at IS NULL AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[taskId,workspaceId,userId,role]);if(!allowed.rowCount)throw new NotFoundException('Tarefa não encontrada')
    const result=await this.database.transaction(async query=>{const added=await query<{id:string;task_id:string;name:string;url:string;created_at:string}>('INSERT INTO task_attachments (id,task_id,name,url) VALUES ($1,$2,$3,$4) RETURNING *',[randomUUID(),taskId,input.name.trim(),input.url.trim()]);await query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'attachment_added',JSON.stringify({attachmentId:added.rows[0].id,name:input.name.trim()}),userId]);return added.rows[0]});const row=result;return{id:row.id,taskId:row.task_id,name:row.name,url:row.url,createdAt:new Date(row.created_at).toISOString()}
  }

  async createChecklistItem(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,title:string):Promise<TaskChecklistItem>{if(!title?.trim())throw new BadRequestException('Informe o item do checklist');const result=await this.database.query<{id:string;task_id:string;title:string;completed:boolean;position:number;created_at:string}>(`INSERT INTO task_checklist_items(id,task_id,title,position) SELECT $1,t.id,$2,COALESCE((SELECT MAX(position)+1 FROM task_checklist_items WHERE task_id=t.id),0) FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=$3 AND p.workspace_id=$4 AND ($6<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$5)) RETURNING *`,[randomUUID(),title.trim(),taskId,workspaceId,userId,role]);const row=result.rows[0];if(!row)throw new NotFoundException('Tarefa não encontrada');await this.database.query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'checklist_added',JSON.stringify({title:row.title}),userId]);return{id:row.id,taskId:row.task_id,title:row.title,completed:row.completed,position:row.position,createdAt:new Date(row.created_at).toISOString()}}
  async updateChecklistItem(workspaceId:string,userId:string,role:WorkspaceRole,id:string,input:{title?:string;completed?:boolean}):Promise<TaskChecklistItem>{if(input.title!==undefined&&!input.title.trim())throw new BadRequestException('Informe o item do checklist');const result=await this.database.query<{id:string;task_id:string;title:string;completed:boolean;position:number;created_at:string}>(`UPDATE task_checklist_items c SET title=COALESCE($2,c.title),completed=COALESCE($3,c.completed) FROM tasks t,projects p WHERE c.id=$1 AND c.task_id=t.id AND t.project_id=p.id AND p.workspace_id=$4 AND ($6<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$5)) RETURNING c.*`,[id,input.title?.trim()??null,input.completed??null,workspaceId,userId,role]);const row=result.rows[0];if(!row)throw new NotFoundException('Item não encontrado');await this.database.query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',row.task_id,input.completed?'checklist_completed':'checklist_updated',JSON.stringify(input),userId]);return{id:row.id,taskId:row.task_id,title:row.title,completed:row.completed,position:row.position,createdAt:new Date(row.created_at).toISOString()}}
  async removeChecklistItem(workspaceId:string,userId:string,role:WorkspaceRole,id:string){const result=await this.database.query(`DELETE FROM task_checklist_items c USING tasks t,projects p WHERE c.id=$1 AND c.task_id=t.id AND t.project_id=p.id AND p.workspace_id=$2 AND ($4<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3)) RETURNING c.task_id`,[id,workspaceId,userId,role]);if(!result.rowCount)throw new NotFoundException('Item não encontrado')}
  async addDependency(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,dependsOnTaskId:string):Promise<TaskDependency>{if(taskId===dependsOnTaskId)throw new BadRequestException('Uma tarefa não pode depender dela mesma');const tasks=await this.database.query<{id:string;project_id:string}>(`SELECT t.id,t.project_id FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=ANY($1::uuid[]) AND p.workspace_id=$2 AND ($4<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[[taskId,dependsOnTaskId],workspaceId,userId,role]);if(tasks.rowCount!==2||tasks.rows[0].project_id!==tasks.rows[1].project_id)throw new BadRequestException('As tarefas precisam pertencer ao mesmo projeto');const cycle=await this.database.query(`WITH RECURSIVE chain(id) AS (SELECT depends_on_task_id FROM task_dependencies WHERE task_id=$1 UNION SELECT d.depends_on_task_id FROM task_dependencies d JOIN chain c ON d.task_id=c.id) SELECT 1 FROM chain WHERE id=$2`,[dependsOnTaskId,taskId]);if(cycle.rowCount)throw new BadRequestException('Essa dependência criaria um ciclo');const result=await this.database.query<{created_at:string}>('INSERT INTO task_dependencies(task_id,depends_on_task_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING created_at',[taskId,dependsOnTaskId]);if(!result.rows[0])throw new BadRequestException('Dependência já adicionada');await this.database.query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'dependency_added',JSON.stringify({dependsOnTaskId}),userId]);return{taskId,dependsOnTaskId,createdAt:new Date(result.rows[0].created_at).toISOString()}}
  async removeDependency(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,dependsOnTaskId:string){const result=await this.database.query(`DELETE FROM task_dependencies d USING tasks t,projects p WHERE d.task_id=$1 AND d.depends_on_task_id=$2 AND d.task_id=t.id AND t.project_id=p.id AND p.workspace_id=$3 AND ($5<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$4))`,[taskId,dependsOnTaskId,workspaceId,userId,role]);if(!result.rowCount)throw new NotFoundException('Dependência não encontrada')}

  async setCustomField(workspaceId:string,userId:string,role:WorkspaceRole,taskId:string,fieldId:string,value:string|number|string[]|null):Promise<TaskCustomFieldValue>{const field=await this.database.query<{type:CustomFieldType;options:CustomFieldOption[]}>(`SELECT f.type,f.options FROM project_custom_fields f JOIN tasks t ON t.project_id=f.project_id JOIN projects p ON p.id=t.project_id WHERE f.id=$1 AND t.id=$2 AND p.workspace_id=$3 AND ($5<>'guest' OR EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$4))`,[fieldId,taskId,workspaceId,userId,role]);if(!field.rowCount)throw new NotFoundException('Campo personalizado não encontrado');const definition=field.rows[0];if(value!==null){if(definition.type==='number'&&(typeof value!=='number'||!Number.isFinite(value)))throw new BadRequestException('Informe um número válido');if(['text','date','single'].includes(definition.type)&&typeof value!=='string')throw new BadRequestException('Valor inválido para o campo');if(definition.type==='multi'&&!Array.isArray(value))throw new BadRequestException('Valor inválido para seleção múltipla');const allowed=new Set(definition.options.map(option=>option.id));if(definition.type==='single'&&!allowed.has(value as string))throw new BadRequestException('Opção inválida');if(definition.type==='multi'&&(value as string[]).some(item=>!allowed.has(item)))throw new BadRequestException('Opção inválida')}if(value===null||value===''||(Array.isArray(value)&&!value.length)){await this.database.query('DELETE FROM task_custom_field_values WHERE task_id=$1 AND field_id=$2',[taskId,fieldId])}else await this.database.query(`INSERT INTO task_custom_field_values(task_id,field_id,value) VALUES($1,$2,$3::jsonb) ON CONFLICT(task_id,field_id) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`,[taskId,fieldId,JSON.stringify(value)]);await this.database.query('INSERT INTO activity_log(id,entity_type,entity_id,action,payload,user_id) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),'task',taskId,'custom_field_updated',JSON.stringify({fieldId}),userId]);return{taskId,fieldId,value}}

  async removeAttachment(workspaceId:string,userId:string,role:WorkspaceRole,id:string):Promise<void>{const result=await this.database.query(`DELETE FROM task_attachments a USING tasks t,projects p WHERE a.id=$1 AND a.task_id=t.id AND t.project_id=p.id AND p.workspace_id=$2 AND ($4<>'guest' OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=$3))`,[id,workspaceId,userId,role]);if(!result.rowCount)throw new NotFoundException('Anexo não encontrado')}
}
